sudo: required
dist: trusty
language: minimal
cache:
  directories:
    - $HOME/docker

services:
  - docker

script:
  - docker-compose run reevoocop
  - docker-compose run rspec
  - docker-compose run rails32
  - docker-compose run rails42
  - docker-compose run rails50
  - docker-compose run grape
  - docker-compose run sinatra

