sudo: false
language: ruby
cache: bundler
before_install:
  - rvm get head
  - gem update --system
  - gem install bundler
install:
  - bundle install -j8 -r3
script:
  - if [[ "${STYLE}" = "true" ]]; then bundle exec rubocop; fi;
  - bundle exec rspec spec
rvm:
  - jruby-9.0.5.0
  - rbx-3.9
  - 2.2.4
env: STYLE=false

matrix:
  fast_finish: true
  include:
    - rvm: 2.3.1
      env: STYLE=true

addons:
  code_climate:
    repo_token: e199bdc9d2cf5ceaa7e46425f118470e43880940098f815a4c972a923102b12b