version: '2'
volumes:
  gems:
    driver: local

services:
  rspec:
    extends:
      file: docker-common.yml
      service: rails
    entrypoint: /usr/src/app/dev-entrypoint.sh
    command: bundle exec rspec
    environment:
      PATH: /usr/src/app/bin:/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
