source "https://rubygems.org"

gem "rails", "3.2.22"

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem "active_model_serializers"
gem "dogstatsd-ruby"
gem "pg"
gem "sapience", path: "../..", require: "sapience/rails"
gem "sentry-raven"
gem "slim-rails"
gem "sneakers"


group :test, :development do
  gem "byebug", platform: :mri
  gem "factory_girl_rails"
  gem "pry-byebug", platform: :mri
  gem "rspec-rails"
  gem "test-unit"
end

group :test do
  gem "fuubar"
  gem "rspec-its"
  gem "simplecov"
  gem "simplecov-json"
end
