---
default:
  filter_parameters:
    - password
    - password_confirmation
  log_executor: single_thread_executor
  log_level: info
  appenders:
    - stream:
        io: STDOUT
        formatter: color

test:
  log_level: warn
  log_executor: immediate_executor
  appenders:
    - stream:
        file_name: log/test.log
        formatter: color

development:
  log_level: debug
  appenders:
    - stream:
        file_name: log/development.log
        formatter: color

production:
  log_level: warn
  appenders:
    - stream:
        file_name: log/production.log
        formatter: json
