# frozen_string_literal: true
source "https://rubygems.org"


gem "pg", "~> 0.15"
gem "rails", "~> 4.2"

gem "active_model_serializers"
gem "dogstatsd-ruby"
gem "sapience", path: "../..", require: "sapience/rails"
gem "sentry-raven"
gem "slim-rails"
gem "sneakers"


group :test, :development do
  gem "byebug", platform: :mri
  gem "factory_girl_rails"
  gem "pry-byebug", platform: :mri
  gem "rspec-rails"
  gem "test-unit"
end

group :test do
  gem "fuubar"
  gem "rspec-its"
  gem "simplecov"
  gem "simplecov-json"
end

group :development do
  gem "spring", "2.0.2"
  gem "web-console", "~> 2.0"
end
