# frozen_string_literal: true
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.
require_relative "lib/ping"
require_relative "lib/ping/db"

require "rspec/core/rake_task"
RSpec::Core::RakeTask.new(:spec)

task default: [:migrate, :spec]

task :migrate do
  Sequel.extension :migration
  Sequel::Migrator.run(Aslan::DB, "db/migrations")
end
