# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bef04432afb761781eb5f21750516ee7becfebe1d495c93514e1207c136aa6a236ebe52ccd648132711c64030c9952df8219e54bc54830d06d34ede1e27d4569

test:
  secret_key_base: 6ede0467fb10c1a498d6ebce120c8dd9e7923c0275e502c752d7fc7b03caed4b2840e8da1a408f5548ed00e42a1a19859da3d4936d3e5e736b46075ac3003948

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
