source "https://rubygems.org"


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "rails", "~> 5.0.0"
# Use sqlite3 as the database for Active Record
gem "pg"
# Use Puma as the app server
gem "puma", "~> 3.0"
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
gem "active_model_serializers"
gem "dogstatsd-ruby"
gem "sapience", path: "../..", require: "sapience/rails"
gem "sentry-raven"
gem "slim-rails"
gem "sneakers"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platform: :mri
  gem "factory_girl_rails"
  gem "pry-byebug", platform: :mri
  gem "rspec-rails"
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem "listen", "~> 3.0.5"
  gem "web-console"
end

group :test do
  gem "fuubar"
  gem "rails-controller-testing"
  gem "rspec-its"
  gem "simplecov"
  gem "simplecov-json"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
